spring.application.name=collaborative-project-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/collaborative_tracker
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080